### ISSUE TITLE
Trouble installing torch 1.13.1

### ISSUE THREAD

**Issue by zblabs** [jgravelle/GroqCasters#1]
As specified in requirements.txt.

ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==1.13.1

I am running windows 11, python 3.11. In an anaconda environment.

**Comment by therealstevewolfe** [comment]
If I am not mistaken, carry on with newer version of torch
`pip install torch`

**Comment by jgravelle** [comment]
Also try:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by zblabs** [comment]
> If I am not mistaken, carry on with newer version of torch `pip install torch`

That worked. I did pip install for all the libraries in requirements.txt and it worked.  I also had to pip install bs4.

Thank you for the assistance.
