### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by limcheekin** [jgravelle/GroqCasters#2]
Please add a LICENSE file.

**Comment by jgravelle** [comment]
Selesai!  Terima kasih kerana bertanya.  Saya harap anda menikmati GroqCasters...!

**Comment by limcheekin** [comment]
Still no license defined?

**Comment by jgravelle** [comment]
![image](https://github.com/user-attachments/assets/1e9867fe-4071-4da4-9b71-19c6c4cf7871)
