### ISSUE TITLE
Something is missing for Windows...

### ISSUE THREAD

**Issue by HyperUpscale** [jgravelle/GroqCasters#4]
For Windows 10 environment we seem to need to use python 3.9 so the exact requirements will match.  Also added bs4.

But then following the steps provided I see these 3 errors.
"python groqcasters.py text.txt D:\AI\GroqCasters\output"

Traceback (most recent call last):
  File "D:\AI\GroqCasters\groqcasters.py", line 5, in <module>
    from pocketgroq import GroqProvider, GroqAPIKeyMissingError, GroqAPIError
  File "D:\AI\GroqCasters\CondaEnvTorchPy9\lib\site-packages\pocketgroq\__init__.py", line 3, in <module>
    from .groq_provider import GroqProvider
  File "D:\AI\GroqCasters\CondaEnvTorchPy9\lib\site-packages\pocketgroq\groq_provider.py", line 11, in <module>
    from .chain_of_thought.cot_manager import ChainOfThoughtManager
ModuleNotFoundError: No module named 'pocketgroq.chain_of_thought'

annotated-types==0.7.0
anyio==4.6.0
audioread==3.0.1
bark==0.1.5
beautifulsoup4==4.12.3
boto3==1.35.35
botocore==1.35.35
bs4==0.0.2
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
colorama==0.4.6
decorator==5.1.1
distro==1.9.0
einops==0.8.0
encodec==0.1.1
exceptiongroup==1.2.2
filelock==3.16.1
fsspec==2024.9.0
funcy==2.0
groq==0.8.0
h11==0.14.0
httpcore==1.0.6
httpx==0.27.2
huggingface-hub==0.25.1
idna==3.10
jmespath==1.0.1
joblib==1.4.2
librosa==0.9.1
llvmlite==0.43.0
numba==0.60.0
numpy==1.22.0
packaging==24.1
platformdirs==4.3.6
pocketgroq==0.3.0
pooch==1.8.2
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
python-dateutil==2.9.0.post0
python-dotenv==0.19.1
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
resampy==0.4.3
s3transfer==0.10.2
scikit-learn==1.5.2
scipy==1.7.3
six==1.16.0
sniffio==1.3.1
SoundFile==0.10.3.post1
soupsieve==2.6
threadpoolctl==3.5.0
tokenizers==0.13.3
torch==1.13.1
torchaudio==0.13.1
tqdm==4.66.5
transformers==4.28.1
typing_extensions==4.12.2
urllib3==1.26.20

**Comment by jgravelle** [comment]
Thanks!  Looks like you need to add GROQ_API_KEY=gsk_whatever12345 to your environment variables...

**Comment by jgravelle** [comment]
Also, do an updated installation of PocketGroq...
